[profile.default]
solc = "0.8.18"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = false
multiline_func_header = "all"
